// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBrs4b4tvZewfdZxAjP5HdlzJXtPfqbiA',
    appId: '1:1098333054428:web:2e136a661f3c23adf09b19',
    messagingSenderId: '1098333054428',
    projectId: 'inspectos-remo',
    authDomain: 'inspectos-remo.firebaseapp.com',
    storageBucket: 'inspectos-remo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbnUmeQ2HGFFd4BCnyL7JNsCeWjJVjvRQ',
    appId: '1:1098333054428:android:4303776f092374bef09b19',
    messagingSenderId: '1098333054428',
    projectId: 'inspectos-remo',
    storageBucket: 'inspectos-remo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7p9rbMeAnIxyiXZnraxY5oS01WWg4IXE',
    appId: '1:1098333054428:ios:0923c75458bdb100f09b19',
    messagingSenderId: '1098333054428',
    projectId: 'inspectos-remo',
    storageBucket: 'inspectos-remo.appspot.com',
    iosBundleId: 'com.example.inspectorxBeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7p9rbMeAnIxyiXZnraxY5oS01WWg4IXE',
    appId: '1:1098333054428:ios:440daa112509b984f09b19',
    messagingSenderId: '1098333054428',
    projectId: 'inspectos-remo',
    storageBucket: 'inspectos-remo.appspot.com',
    iosBundleId: 'com.example.inspectorxBeta.RunnerTests',
  );
}
